### ISSUE TITLE
IRC Fails to disconnect after calling disconnect.

### ISSUE THREAD

**Issue by noah-** [meebey/SmartIrc4net#29] opened 2014-12-25 21:25 UTC
When I call client.Disconnect the program hangs for over 30 seconds and fails to disconnect.
I've tried with using Listen and ListenOnce with a flag (triggered by command sent).

**Comment by meebey** [comment] 2015-01-27 17:56
This is a duplicate of #4

**Closed by meebey** 2015-01-27 17:56 UTC
